- e.observability.md
- f.services.md
Trivial corrections for wrong parameters
> Some corrections

- d.configuration.md
Little contribution from my side. I have made correction in answer # 4 and also little correction made in Q&A # 5.
Regards,
> small contribution in d.configration.md file

- e.observability.md
- g.state.md
I had problems with a couple of solutions to some of the questions, I believe these small changes should fix them
> Fixed up a couple of typos in solutions

- a.core_concepts.md
you can use --command option instead of editing generated yaml file
> remove yaml edit part

- a.core_concepts.md
Fixed minor typo.
* not working
`kubectl describe nginx`
* working
`kubectl describe po nginx`
p.s. thank you for the great content!
> Added "po" with describe command

- a.core_concepts.md
Also pulled in https://github.com/dgkanatsios/CKAD-exercises/pull/15 - credit to @abdennour
> Added few alternatives to core_concepts

- c.pod_design.md
Add alternative commands for future deprecated `run` command in c.pod_design.md
> Add alternative command for deprecated run command

- d.configuration.md
we should create it, right? :P
> create serviceaccount command

- f.services.md
> add minikube ip comment

- a.core_concepts.md
The connection can be of various types. So, added the specifics.
> Added more specifics to the question

- f.services.md
- Enriched the question definition to add more clarity
- Added commands to delete the service and the pod as per the ask
> Enriched the question

- f.services.md
Added one more approach to create a deployment using more elegant way.
> Added more elegant option for the answer

- d.configuration.md
I believe that the cli will help people passing the CKAD because they need to be as fast to solve questions.
> encourage usage of cli instead of manual operation

- a.core_concepts.md
I think there could be an extra space in this solution. If I'm wrong, my apologies.
> fix: typo in example solution

- c.pod_design.md
Adds docs reference for labels section
/cc @dgkanatsios 
Thanks 🙌
> chore: adds docs reference for labels section

- c.pod_design.md
Example on how to control job termination and cleanup. That's in the manifest of the last version of the certification
> Controlling Job termination

- b.multi_container_pods.md
Added short one-liner to connect to second container and 'ls'
> Added short one-liner to connect to second container and 'ls'

- c.pod_design.md
added one more way of showing label columns & selectors
> --label-columns & --selector

- c.pod_design.md
> `describe` does not support specifying output format

- g.state.md
to match the previous question; otherwise it may not be bounded
> change storageClassName to normal

- c.pod_design.md
Add one more exercise for CronJob.
> Update Pod Design section

- c.pod_design.md
This will fix the label selector. 
```
-l, --selector='': Selector (label query) to filter on
-L, --label-columns=[]: Accepts a comma separated list of labels that are going to be presented as columns.
```
> Fixed label selector

- c.pod_design.md
- g.state.md
1. Update to include another way to schedule a pod on a specific node, using node affinity.
2. Fix #97 with a question & a short explanation.
> Pod design and state update

- b.multi_container_pods.md
- c.pod_design.md
Add new multi container exercise with:
- initContainer
- shared volume
Example from: https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-initialization/#create-a-pod-that-has-an-init-container
> Add new multi container exercise

- a.core_concepts.md
- b.multi_container_pods.md
- d.configuration.md
- e.observability.md
- f.services.md
- g.state.md
Update all the dry-run commands to make them compatible with the latest version of `kubectl` command.
> update all the dry-run commands

- a.core_concepts.md
@dgkanatsios  Adding PR for Issue #100 for your feedback
> Issue #100: Updating the question to expose the port 80

- c.pod_design.md
The additional command for creating deployment with replicas and port.
> deployment with replicas and port

- f.services.md
simpler version of deploy command
> Simpler version of deploy command

- a.core_concepts.md
Added `-n mynamespace` to command to generate yaml
> Added -n mynamespace to generate yaml command

- b.multi_container_pods.md
Original multi container task description has few confuses. This commit has fixed it.
> Multi-container description fix

- c.pod_design.md
This is so the next step makes more sense.
IE,
```bash
kubectl logs pi-**** # get the pi numbers
kubectl delete job pi
```
> Add specific name to job

- c.pod_design.md
Set newer image versions for `nginx`, in `c.pod_design.md` exercises
> Set newer nginx images for c.pod_design.md

- c.pod_design.md
Using the full command to avoid confusion.
> changed 'k' to 'kubectl'

- f.services.md
A better understanding of labeling the deployments.
> added 'kubectl label' for deployment 'foo'

- c.pod_design.md
Reverts dgkanatsios/CKAD-exercises#175
> Revert "Using startingDeadlineSeconds instead of activeDeadlineSeconds"

- README.md
- c.pod_design.md
Credits to @jhchong92 for finding the error on the CronJob questions on #213 
Added an additional CronJob question so both `activeDeadlineSeconds` and `startingDeadlineSeconds` are described.
> fix on the cronjob questions, based on #213

- g.state.md
> 🐛 Fix missing leading slash when copying passwd

- b.multi_container_pods.md
It's a small fix to make the reading more natural
> docs: Fix typos. Missing articles and adjust preposition

- c.pod_design.md
- e.observability.md
* keep the docs breadcrumb and links as same with the newest official docs
* format some space characters
> Update some doc links and breadcrumb

- d.configuration.md
- h.helm.md
> Typo check

- d.configuration.md
- h.helm.md
- alternative yaml added to create cpu & memory resources as imperative command already provided in solution.
> yaml added at Requests & Limits  

- i.crd.md
Hi reviewers:
This is a minimal improvement for CRD exercise.
Please helps to review it, thanks 🙏
Alex
> add description for CRD exercise

- d.configuration.md
this line not needed in the yaml
> correction: resources section was repeated

- e.observability.md
Linked to this issue: https://github.com/dgkanatsios/CKAD-exercises/issues/282
> Improved solution of 4th exercise of e.observability.md file

- e.observability.md
command formatted as code to make dollar signs visible
> fix command format  (e.observability.md#logging)

- h.helm.md
```
helm install -f myvalues.yaml my redis ./redis
```
↓
```
helm install -f myvalues.yaml myredis ./redis
```
> fix helm command

- h.helm.md
@dgkanatsios: Thank you for this amazing repo!
I've added a few new tasks in the context of Helm, which I thought might be useful to know how to solve:
- Add Bitnami repo to Helm
- Write contents of values.yaml for a chart to stdout
- Install a chart with override value as argument
> Add 3 new Helm tasks

- c.pod_design.md
* Add a missing problem in the Cron section
* Wrap an answer that isn't hidden
> Add a missing problem title: "Create the same cron job again, and ..."

- h.helm.md
fix typo "bitname" to "bitnami"
> update h.helm.md typo "bitname" to "bitnami"

- g.state.md
I did a bit of research and turns out awk works too. 
Credit to: https://stackoverflow.com/questions/2609552/how-can-i-use-as-an-awk-field-separator
> Awk alternative

- b.multi_container_pods.md
Updating Pod IP to fetch using jsonpath
Init Container is failing, http://neverssl.com/online is not reachable, so just adding dummy text to the html file
> Updating podIP and fixing init container issue

- d.configuration.md
Add limit range information about ckad exam
> Add limit range information

- README.md
- c.pod_design.md
Recent March 2023 exam had this question
> Create a job from Cronjob

- d.configuration.md
Adds a section for ResourceQuotas. Shows creation of a ResourceQuota resource and attempting to create a pod that has resource requests/limits that exceed the quota.
> Add exercise for ResourceQuotas

- b.multi_container_pods.md
- d.configuration.md
1. Add exam tips
2. Create some secrets excercises.
- Create a Secret and Consume it as Volume
- Create a Secret and Consume it as Environment Variables
> Add exam tips and Secrets excercises

- d.configuration.md
The prompt should include the details required to complete the task, one should not have to review the solution in order to determine what types of constraints should be configured.
> Update for clarity

- c.pod_design.md
`--force` can cause a lot of pain and suffering when used incorrectly, best not to use it without an explicit purpose
> Don't use --force

- e.observability.md
Fixed formatting on ports section
> Fixed formatting bug in e.observability.md

- b.multi_container_pods.md
- c.pod_design.md
- g.state.md
fix some typos like targetting, shoutdown and some other improvements
> fix some typos like targetting, shoutdown and some other improvements

- j.podman.md
This shows how to create an image without running a container, and how to export a container.
> Adds the create and export command to podman

- c.pod_design.md
In module c I added a more invasive option for editing the pod label, just for completness sake.
> Add option to edit pod label

- c.pod_design.md
The ordering of the jobs section didn't make sense because it says to create the same job, but it was referring to the job before last.
> c.pod_design.md: reorder jobs

- d.configuration.md
Fix "Create an nginx pod that uses 'myuser' as a service account"
> Kubernetes 1.24+, "Create an nginx pod that uses 'myuser' as a service account" 
