dgkanatsios/CKAD-exercises

a.core_concepts.md

possibly a newer version of k8s requires specificity on type of object for updating the image. i couldn't get it to work with the current example.
my kubectl client and server version: v1.12
updated based on documentation from `kubectl set images --help`
```
Examples:
kubectl set image deployment/nginx busybox=busybox nginx=nginx:1.9.1
```

updated set image for changing to nginx:1.7.1

---

g.state.md

Hi,
Thank you for the exercises. They helped me to pass the exam.
I find two small typos in `State persistence` section. Since Kubernetes uses `Gi` instead of `GB`, and the question answer doesn't match question, this PR updates the storage units.
Thanks,
Chenyuan

Update from GB to Gi

---

c.pod_design.md

You reference `kubectl logs perl-**** # get the pi numbers` which references the container image name, but the pod name `pi-****`. A minor issue but could be confusing.

Fix log check for job with counting pi digits

---

README.md
a.core_concepts.md
c.pod_design.md
d.configuration.md
e.observability.md
f.services.md
g.state.md

Added links to official documentation before an exercise. You can check the final look at my fork https://github.com/askrht/CKAD-exercises
During the exam, you are allowed to keep only one other browser tab open to refer official documentation. Make a mental note of the breadcrumb at the start of the excercise section, to quickly locate the relevant document in kubernetes.io. It is recommended that you read official documents before attempting exercises below it.

Added links to official documentation before an exercise.

---

e.observability.md
g.state.md

First of all, thank you for the great documentation.
I will use it effectively when taking the exam.
I was able to fix some of the things I was interested in practicing.
I did in the following version.
```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

Modify command and description

---

c.pod_design.md

Flag --export has been deprecated, This flag is deprecated and will be removed in future. The alternative is a simple -o yaml and post-processing the yaml to remove undesired state information.

Removed deprecated --export flags

---

a.core_concepts.md

There is no reason to create a shell and run the wget inside of this shell, just call wget directly (since the shell is the command and wget will be an argument).

Simplify the wget call

---

a.core_concepts.md

I got very confused about the questions and could not understand that the question was referring to the previously created nginx pod. So, I thought to add this line to help others.

Cleared the instructions to avoid confusion

---

d.configuration.md

I found the question confusing as "UID" is also a field under metadata. I created a pod with that and found that this question was actually referring to user ID to run the pod with.

Updated the question to avoid the confusion

---

d.configuration.md

Isn't it better to remove `--export` flag from this command as it's deprecated?

"export" is a deprecated flag

---

e.observability.md

I was doing the exercise and there is no need to expose the container port on kubernetes v1.15.1

no need to expose port for probes

---

d.configuration.md

`-d` switch is not a valid option for `base64` command. It should be either `base64 -D` or `base64 --decode`.

Corrected the command

---

c.pod_design.md

Based on my understanding of the "**default**" command, it's the one that is set under `ENTRYPOINT` section of the container image. So, when you want to run that container with its default command, we should not override that default command while creating the container from that image. But here, when we use `-- perl ...` in either `create job` or `run` commands, it would override the default command of the job and does not just update the `args` of the default command. I hope this makes sense. Otherwise, feel free to reject the pull request.

Changed the question

---

c.pod_design.md

As the first revision is for a new deployment.
The second revision is for version nginx:1.7.9
The third revision is for the rollout undo.
The fourth revision is for the wrong version: nginx:1.91

Correcting revision number

---

a.core_concepts.md
d.configuration.md
f.services.md

This pull request intends to: 
- Cleanup `--export` repository references (issue #74)
- Add more syntax options to `output` objects to yaml.
---
> The flag --export is used to get a resource's YAML without cluster specific information.
As mentioned in the [Kubernetes Changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#deprecations), the `--export` flag for the kubectl get command is already deprecated and will be removed in v1.18. (#[73787](https://github.com/kubernetes/kubernetes/pull/73787))

Cleanup deprecated --export flag

---

e.observability.md

Change `periodSeconds` to a value different than it's default.
From pods.spec.containers.livenessProbe:
```
periodSeconds        <integer>
How often (in seconds) to perform the probe. Default to 10 seconds. Minimum
value is 1.
```

Change periodSeconds to non default value

---

f.services.md

YAML 1.1 parsers interpret strings that match the following regular expressions as Booleans. ie: using true (or variations thereof)
https://yaml.org/type/bool.html:
```
y|Y|yes|Yes|YES|n|N|no|No|NO
|true|True|TRUE|false|False|FALSE
|on|On|ON|off|Off|OFF
```
The result is that trying to create a network policy using the suggested label will return:
```
Error from server (BadRequest): error when creating "network.yaml": NetworkPolicy in version "v1" cannot be handled as a NetworkPolicy: v1.NetworkPolicy.Spec: v1.NetworkPolicySpec.Ingress: []v1.NetworkPolicyIngressRule: v1.NetworkPolicyIngressRule.From: []v1.NetworkPolicyPeer: v1.NetworkPolicyPeer.PodSelector: v1.LabelSelector.MatchLabels: ReadString: expects " or n, but found t, error found in #10 byte of ...|"access":true}}}]}],|..., …
```

Use label value without ambiguous meaning

---

f.services.md

If runnig temporary pod with command to check if service/pod is accessible:
`kubectl run busybox --image=busybox --rm -it --restart=Never -- wget -O- http://nginx:80`
And connection is refused. 
Than temporary pod hangs and isn't terminated (because command is still in progress).
I suggest to add `--timeout` option in this case. It will let terminate pod execution and will show that connection fails quickly:
```
master $ kubectl run busybox --image=busybox --rm -it --restart=Never -- wget -O- http://nginx:80 --timeout 2
If you don't see a command prompt, try pressing enter.
Connecting to nginx:80 (10.99.87.48:80)
wget: download timed outpod "busybox" deleted
pod default/busybox terminated (Error)
```

Add --timeout option for wget in temporary pods

---

c.pod_design.md

In one place the instruction says that activeDeadlineSeconds has to be set to 17 seconds, but in another that value is 30.

Fix activeDeadlineSeconds value inconsistency

---

a.core_concepts.md

Hello,
This is a little contribution.
In the first changed instruction, the $NGINX_IP environment variable was substituted on the command interpretation, not during the command execution.
If you like contribution, I may propose another order in exercises.

Improved Core Concepts documentation/sample.

---

c.pod_design.md

kubectl get pods  -o custom-columns=Name:metadata.name,ANNOTATIONS:metadata.annotations.description
is a more distinctive way of checking the annotations - probably better than to grep the result of kubectl describe - and certainly more straight forward as jsonpath :-)

add additional way for checking "annotations"

---

c.pod_design.md

From the kubectl help documentation, -l is used as a selector and -L is used to show labels as a column. Updated the markdown to have the correct argument.

Fixed --label-columns shorthand to -L

---

f.services.md

The goal of this PR is to fix a small typo in `Services & Deployment` section

Fix a typo when exposing a deployment in Services & Deployment section

---

b.multi_container_pods.md

Issue is caused by busybox's wget, which cannot validate SSL connections. The easy solution is to use a http page that doesn't redirect to https, which kubernetes.io does, but http://neverssl.com/online does not.  To replicate the problem create the box pod with the initContainer and the regular Container as per answer example and then run "kubectl logs box -c box" to see the error messages. The status of the pod will also be "Init:CrashLoopBackOff" with constant restarts because it fails at the init stage.
Reference: https://github.com/moby/moby/issues/41348

Fixed TLS certificate validation not implemented

---

g.state.md

Ref: https://github.com/dgkanatsios/CKAD-exercises/issues/142

removing leading '/' from kubectl cp busybox:./etc/passwd

---

c.pod_design.md
f.services.md

Use Kubectl logs job/<JobName> directly rather than getting the pod name and then getting the logs of the pod

getting job logs directly

---

g.state.md

Thank you for sharing awesome exercises 👍
I found that markdown link (about **Persistent Volumes**) format is broken.
>- State Persistence (8%)
>    - Define volumes
>        - Create a second pod which is identical with the one you just created (you can easily do it by changing the 'name' property on pod.yaml). Connect to it and verify that '/etc/foo' contains the 'passwd' file. Delete pods to cleanup. Note: If you can't see the file from the second pod, can you figure out why? What would you do to fix that?
So I fixed markdown link format correctly.
Thank you :)

Updated g.state.md : fixed markdown link format

---

c.pod_design.md

Thank you for sharing awesome exercises 👍
I found that we can use the following `kubectl` command more clearly for the question. Because the question needs to check the annotation of `nginx1`.
>- Pod design (20%)
>    - Deployments
>      - Check the annotations for pod nginx1
The current `kubectl` command gets annotations for all pods. This is my example.
```sh
$ kubectl get pods -o custom-columns=Name:metadata.name,ANNOTATIONS:metadata.annotations.description
Name                       ANNOTATIONS
busybox                    <none>
busybox-1613632620-c6zfl   <none>
busybox-1613632680-qw9hx   <none>
busybox-1613632740-48cl6   <none>
nginx1                     my description
nginx2                     my description
nginx3                     my description
```
So I updated `kubectl` …

Updated c.pod_design.md : more clear kubectl command

---

a.core_concepts.md

Given the command `kubectl run nginx --image=nginx --restart=Never --dry-run=client -n mynamespace -o yaml` the resulting yaml is missing the `namespace` key. This change adds the missing namespace key. Also since the namespace key is now present in the yaml I've removed it from the apply since it's not needed there.

Add missing ns

---

a.core_concepts.md
c.pod_design.md
f.services.md

In the second exercise of core concepts, the solution  asks to run the command:
`kubectl run nginx --image=nginx --restart=Never --dry-run=client -n mynamespace -o yaml > pod.yaml`
However the posted resulting YAML is currently missing the namespace, which does not match the result of running the command above. Fixed by adding the namespace to the yaml

Added missing namespace in posted YAML

---

b.multi_container_pods.md

When following the answer, i ran into the issue that the "box" pods already exists. We created it with the yaml file, therefore i needed to change the name of the wget-executing container to make it work. Should'nt be a problem for most of the folks preparing for the exam, but to make it "copy-pastable" i changed the name from "box" to "box-test" as we are testing our "box" pod.

Update b.multi_container_pods.md to make the commands almost copy pastable.

---

f.services.md

Adds a bash oneliner to create temporary containers to fetch the required result.

Docs: oneliner to launch multiple pods to fetch result

---

c.pod_design.md

This PR leverages bash oneliner to generate 3 pods.

Docs: add oneliner to generate numbered pods

---

c.pod_design.md

Thank you for sharing awesome exercises 👍
I found that when we set wrong image name will get error `ErrImagePull` or `ImagePullBackOff` on exercise below.
>- Pod design (20%)
>    - Deployments
>      - Verify that something's wrong with the rollout
This is my sample logs.
```sh
$ kubectl get pods nginx-d645d84b6-ftbwc -w
NAME                    READY   STATUS         RESTARTS   AGE
nginx-d645d84b6-ftbwc   0/1     ImagePullBackOff   0          77s
nginx-d645d84b6-ftbwc   0/1     ErrImagePull       0          108s
nginx-d645d84b6-ftbwc   0/1     ImagePullBackOff   0          2m1s
nginx-d645d84b6-ftbwc   0/1     ErrImagePull       0          3m12s
nginx-d645d84b6-ftbwc   0/1     ImagePullBackOff   0          3m25s
nginx-d645d84b6-ftbwc   0/1     ErrImagePull       0          6m7s …
```

Updated c.pod_design.md : added status when pull error occurs

---

d.configuration.md

At this PR (https://github.com/dgkanatsios/CKAD-exercises/pull/65), `-n` option was added to echo command in the first instruction of mysecret2 section, but subsequent instructions weren't updated so the base64 encoded value is not corresponding now.
* Changed base64 encoded value to correspond to the previous `echo -n admin > username` .
* Added `-n` to echo because echo without `-n` adds newline. It is not good for operations like value decoding.
* Removed the unnecessary newline from the `-o jsonpath` example.
Supporting operation logs.
```
ckad $ echo -n admin > username
ckad $ kubectl create secret generic mysecret2 --from-file=username
secret/mysecret2 created
ckad $ kubectl get secrets mysecret2 -o yaml
apiVersion: v1
data:
username: YWRtaW4=  # <= this
kind: Secret
metadata: …
```

Made mysecret2 value correspond to the previous operation.

---

c.pod_design.md

**activeDeadlineSeconds** causes the following error:
error: error validating "cronjob2.yaml": error validating data: ValidationError(CronJob.spec): unknown field "activeDeadlineSeconds" in io.k8s.api.batch.v1beta1.CronJobSpec; if you choose to ignore these errors, turn validation off with --validate=false
Changing it to **startingDeadlineSeconds**

Using startingDeadlineSeconds instead of activeDeadlineSeconds

---

d.configuration.md

1. Use of `--requests` and `--limits` flags in the imperative `run` command is deprecated and will be removed in the future release. Instead, the imperative `set resources` command can be used in combination with the `run` command.
2. Corrected the typo in the Service Account creation.

Alternative option - resources and typo connection

---

c.pod_design.md

Addition tested on K8s `v1.19.11` with kubectl `v1.22.1`

Add alternate way of checking Pod annotations

---

c.pod_design.md

```
kubectl wait --for=condition=complete --timeout=300 job pi
```
Gives me the following error:
```
Error: invalid argument "300" for "--timeout" flag: time: missing unit in duration "300"
```
&nbsp;
```
debian:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

add unit to timeout wait

---

f.services.md

To save folks some previous cycles and head banging - this example won't work with a default AKS cluster. Ie. everything gets created, but traffic flows uninterrupted.

Added a note about netpols enforcement

---

d.configuration.md

Using the included solution based on `kubectl run` with the `--serviceaccount` option, I got the following message running on a k3s cluster:
`Flag --serviceaccount has been deprecated, has no effect and will be removed in 1.24.`

Remove --serviceaccount solution

---

f.services.md

`kubectl get endpoints foo` lists IPs of replica _pods_, not nodes.

Fixed typo in comment of 'expose deployment' question

---

c.pod_design.md

The [CKAD Curriculum](https://github.com/cncf/curriculum/blob/master/CKAD_Curriculum_v1.23.pdf) (v1.23) mentions between the domains of the exam the capacity to "Use Kubernetes primitives to implement common deployment strategies (e.g. blue/green or canary)": I propose to add a simple exercise to implement natively (i.e. without an ingress controller or service mesh) a canary deployment. It seems that a similar question came out in a candidate's exam: see issue #233.

Add exercise for canary deployment

---

c.pod_design.md
j.podman.md

A new topic in the exam [syllabus](https://github.com/cncf/curriculum/blob/master/CKAD_Curriculum_v1.23.pdf) (v1.23) deals with the ability to *define, build and modify container images*. I propose to add a set of exercises to cover this topic by using `podman` since also the LFD259 course uses it in the labs in favour of or besides`docker`. I'm not really sure if both or just of the two commands are available in the exam environment, since I have to still sit the exam, but anyway they are quite interchangeable as stated in the little intro to the exercises.

Add exercises for managing container images

---

j.podman.md

`curl 0.0.0.0:8080` didn't print "Hello, World!" because the Dockerfile didn't write "Hello, World!" into `index.html`.

Fixed the command in Dockerfile (j.podman.md)

---

c.pod_design.md

The usage of the latest perl image version in [this](https://github.com/dgkanatsios/CKAD-exercises/blob/main/c.pod_design.md#create-a-job-named-pi-with-image-perl-that-runs-the-command-with-arguments-perl--mbignumbpi--wle-print-bpi2000) exercise leads to the following error:
``` Can't use an undefined value as an ARRAY reference at /usr/local/lib/perl5/5.36.0/Math/BigInt/Calc.pm line 1049.```
I modified the description of the exercise to point to the image version that is mentioned in the solution.

Specified the perl image version in Jobs exercise - to avoid errors

---

d.configuration.md

Added `--` for the command.
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.

fix command in Secret section

---

e.observability.md

According to the 4th question, the output should be in the format of `<namespace>/<pod name>`. The previous `awk` solution does not exactly follow the format, and the `kubectl get events -A` could output the duplicated events if some Pods are restarting over and over again due to the different `restartPolicy`s.

improve the answer to the 4th question of the observability section

---

b.multi_container_pods.md
c.pod_design.md
f.services.md
g.state.md
i.crd.md

$ alias k=kubectl
% k get operators 
NAME              AGE
operator-sample   11s
% k get operator 
NAME              AGE
operator-sample   15s
% k get op      
NAME              AGE
operator-sample   26s
above command generates the same o/p , updated version should be 
kubectl get operators
or
kubectl get operator
or
kubectl get op

Corrected grammar in Listing operator section 

---

d.configuration.md

At official kubernetes webpages, I can see double quotation marks at cpu resources. So I add this,
example at kubernetes websites:
apiVersion: v1
kind: Pod
metadata:
name: frontend
spec:
containers:
- name: app image: images.my-company.example/app:v4 resources: requests: memory: "64Mi" cpu: "250m" limits: memory: "128Mi" cpu: "500m"
- name: log-aggregator image: images.my-company.example/log-aggregator:v6 resources: requests: memory: "64Mi" cpu: "250m" limits:
memory: "128Mi"
cpu: "500m"

Add double quotation mark

---

README.md

As of June 2022, personal browser bookmarks are not allowed anymore. The browser within the exam environment must be used to access the K8s docs.
> Personal browser bookmarks (such as bookmarked links to YAML files) will not be accessible within the PSI Secure Browser.
Links to CNCF documentation, considered most helpful to complete your work, have been added to a Quick Reference box within each item’s instructions. Access to [published Resources Allowed](https://docs.linuxfoundation.org/tc-docs/certification/certification-resources-allowed#certified-kubernetes-administrator-cka-and-certified-kubernetes-application-developer-ckad) will still be permitted within the Exam Environment.
https://training.linuxfoundation.org/bridge-migration-2021/
This change is also reflected in the …

Update info about allowed resources

---

c.pod_design.md

Hello, 
In the Pod Design section in the last exercice : https://github.com/dgkanatsios/CKAD-exercises/blob/main/c.pod_design.md#implement-canary-deployment-by-running-two-instances-of-nginx-marked-as-versionv1-and-versionv2-so-that-the-load-is-balanced-at-75-25-ratio 
In the solution it is needed to check if the deployment was successful by using the command : 
`curl $(kubectl get svc my-app-svc -o jsonpath="{.spec.clusterIP}")` , however this command does not work if you don't have a nodePort Service to expose it to your local machine.
My suggestion is to test the deployment from whitin a pod by using a busyBox image and the `wget` command.
This is also a solution to the issue : https://github.com/dgkanatsios/CKAD-exercises/issues/281

update c.pod-design.md : test deployment from within a pod

---

f.services.md

I found out that `kubectl create deploy [Name]` will add label `app=[Name]` by default so the step I comment is not mandatory.

Comment on optional step for adding label

---

b.multi_container_pods.md

The instructions and the yaml are different.

Add command in md instructions to yaml init container

---

c.pod_design.md

Split out pod placement exercises from the label/annotations exercises, but still include them in pod design.
Add exercises for pod placement using taints, tolerations, and nodeSelector.
GH made the diff look worse than it is. Moved one exercise and added a few in pod placement

Add taints and tolerations exercises

---

c.pod_design.md

Fix pod yaml for https://github.com/dgkanatsios/CKAD-exercises/blob/main/c.pod_design.md#create-a-pod-that-will-be-placed-on-node-controlplane-use-nodeselector-and-tolerations
Error from server (BadRequest): error when creating "pod.yaml": Pod in version "v1" cannot be handled as a Pod: strict decoding error: unknown field "spec.image"

Fix pod on control-pane

---

d.configuration.md

namespace field missing in YAML file. which will make the resource to be deployed on the default namespace instead of the indented one

Update missing namespace field in d.configuration.md

---

j.podman.md

`podman` no longer supports `docker.io` as a default registry, so the `Dockerfile` should mention it explicitly.
The old behaviour can be restored by adding a config to `/etc/containers/registries.conf`:
```sh
unqualified-search-registries = ["docker.io"]
```
but I believe that specifying a fully-qualified name is a more pragmatic way to go.
The solution comes from this [SE post](https://unix.stackexchange.com/a/701785).  
Also see the related documentation for [`containers-registries.conf`](https://github.com/containers/image/blob/main/docs/containers-registries.conf.5.md#note-risk-of-using-unqualified-image-names)

Update Dockerfile in j.podman.md

---

d.configuration.md

The Secrets question
> Create a Secret named 'ext-service-secret' in the namespace 'secret-ops'. Then, provide the key-value pair API_KEY=LmLHbYhsgWZwNifiqaRorH8T as literal.
had some issues with the bash commands shown:
1. `$ns` was defined but not used; instead, `-n secret-ops` was reiterated in the command.
2. `$do` was not defined but used. Unless you read the really out of context tip at the top of the page and remembered it, you would know how to define `$do` but I didn't.
This PR is to clarify that part of the question and improve the commands.

fix(configuration): fix bash commands in secrets question

---

c.pod_design.md

Since the owner=marketing annotation still exists on pod/nginx2

Adding missing owner annotation to command

---

a.core_concepts.md

On a mac m1 setting the image to 1.7.1 fails due to not supporting the arm64 architecture. Bumping the image tag to a more recent version resolves the issue. resolves #351

Bump nginx image tag to support multiple architectures

---

d.configuration.md

In some places there was a reference to namespace "one" but it should be "limitrange".

Replaces ns name for ns limitrange

---

d.configuration.md

Hi,
While practicing I noticed the resource definition in [this exercise](https://github.com/dgkanatsios/CKAD-exercises/blob/main/d.configuration.md#create-an-nginx-pod-that-requests-250mi-of-memory-in-the-limitrange-namespace) seems to have an incorrect namespace. 
It's also necessary to specify the limit for the pod's memory, and this has to be within the range of the LimitRange defined in the namespace

Fix limit ranges configuration exercise

---

g.state.md

Small typo - "this storage class" doesn't really make sense as the storage class is specified later in the sentence, and the task is about creating a PVC for the PV created in the previous task.

Fix typo in persistent storage tasks

---

b.multi_container_pods.md

`neverssl.com` was referenced in one of the exercises but it is not accessible anymore (it can be verified for example with https://www.isitdownrightnow.com/neverssl.com.html).
The issue was already fixed in https://github.com/dgkanatsios/CKAD-exercises/pull/313, but the instructions of the exercise weren't updated at the time. Later in https://github.com/dgkanatsios/CKAD-exercises/pull/315 the changes of https://github.com/dgkanatsios/CKAD-exercises/pull/313 were reverted to a non-working solution of the exercise.
This pull request reverts https://github.com/dgkanatsios/CKAD-exercises/pull/315 so `neverssl.com` isn't used, and updates the exercise instructions to match the solution.

Fix multi container neverssl exercise

---

c.pod_design.md

By this sample, we can learn and practice `and` and `not` operations in the get pods command.

add a new get pod sample
